// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PastisserieAPI.Infrastructure.Data;

#nullable disable

namespace PastisserieAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260201231859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("CarritosCompra");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CarritoItems");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasProducto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Descripcion = "Tortas y pasteles",
                            Nombre = "Tortas"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Descripcion = "Variedad de panes artesanales",
                            Nombre = "Panes"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Descripcion = "Postres y dulces",
                            Nombre = "Postres"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Descripcion = "Galletas caseras",
                            Nombre = "Galletas"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Descripcion = "Productos personalizables",
                            Nombre = "Personalizados"
                        });
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.DireccionEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barrio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsPredeterminada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DireccionesEnvio");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDespacho")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroGuia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.HasIndex("RepartidorId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Relleno de arequipe",
                            Nombre = "Arequipe",
                            PrecioAdicional = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Crema de chocolate belga",
                            Nombre = "Crema de chocolate",
                            PrecioAdicional = 7000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Fresas naturales",
                            Nombre = "Fresas frescas",
                            PrecioAdicional = 8000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Variedad de frutas",
                            Nombre = "Frutas mixtas",
                            PrecioAdicional = 10000m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Chispas de chocolate",
                            Nombre = "Chispas de chocolate",
                            PrecioAdicional = 3000m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Descripcion = "Nueces tostadas",
                            Nombre = "Nueces",
                            PrecioAdicional = 6000m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Descripcion = "Coco natural rallado",
                            Nombre = "Coco rallado",
                            PrecioAdicional = 4000m
                        });
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.MetodoPagoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPredeterminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoMetodoPagoId")
                        .HasColumnType("int");

                    b.Property<string>("TokenPago")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UltimosDigitos")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoMetodoPagoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MetodosPagoUsuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLeida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DireccionEnvioId")
                        .HasColumnType("int");

                    b.Property<bool>("EsPersonalizado")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<string>("NotasCliente")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DireccionEnvioId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Pedidos_Estado");

                    b.HasIndex("FechaPedido")
                        .HasDatabaseName("IX_Pedidos_FechaPedido");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Pedidos_UsuarioId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PedidoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CambiadoPor")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoHistoriales");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PedidoItems");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PersonalizadoConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diseno")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Forma")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagenReferenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstruccionesEspeciales")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Niveles")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sabor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tamano")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("PersonalizadoConfigs");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PersonalizadoConfigIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalizadoConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("PersonalizadoConfigId");

                    b.ToTable("PersonalizadoConfigIngredientes");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CategoriaProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsPersonalizable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_Productos_Categoria");

                    b.HasIndex("CategoriaProductoId");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Productos_Nombre");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobada")
                        .HasColumnType("bit");

                    b.Property<int?>("AprobadaPor")
                        .HasColumnType("int");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Usuario"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Domiciliario"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Gerente"
                        });
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.TipoMetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposMetodoPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Pago en efectivo contra entrega",
                            Nombre = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Pago con tarjeta de crédito",
                            Nombre = "Tarjeta de Crédito"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Pago con tarjeta de débito",
                            Nombre = "Tarjeta de Débito"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Descripcion = "Transferencia bancaria",
                            Nombre = "Transferencia"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Descripcion = "Pago electrónico PSE",
                            Nombre = "PSE"
                        });
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.UserRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoCompra", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithOne("CarritoCompra")
                        .HasForeignKey("PastisserieAPI.Core.Entities.CarritoCompra", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoItem", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.CarritoCompra", "Carrito")
                        .WithMany("Items")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.Producto", "Producto")
                        .WithMany("CarritoItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.DireccionEnvio", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Envio", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithOne("Envio")
                        .HasForeignKey("PastisserieAPI.Core.Entities.Envio", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Repartidor")
                        .WithMany("EnviosAsignados")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Factura", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithOne("Factura")
                        .HasForeignKey("PastisserieAPI.Core.Entities.Factura", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.MetodoPagoUsuario", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.TipoMetodoPago", "TipoMetodoPago")
                        .WithMany("MetodosPagoUsuarios")
                        .HasForeignKey("TipoMetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("MetodosPago")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Notificacion", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Pedido", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.DireccionEnvio", "DireccionEnvio")
                        .WithMany("Pedidos")
                        .HasForeignKey("DireccionEnvioId");

                    b.HasOne("PastisserieAPI.Core.Entities.MetodoPagoUsuario", "MetodoPago")
                        .WithMany("Pedidos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DireccionEnvio");

                    b.Navigation("MetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PedidoHistorial", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithMany("Historial")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PedidoItem", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.Producto", "Producto")
                        .WithMany("PedidoItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PersonalizadoConfig", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithOne("PersonalizadoConfig")
                        .HasForeignKey("PastisserieAPI.Core.Entities.PersonalizadoConfig", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PersonalizadoConfigIngrediente", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Ingrediente", "Ingrediente")
                        .WithMany("ConfiguracionesPersonalizadas")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.PersonalizadoConfig", "PersonalizadoConfig")
                        .WithMany("Ingredientes")
                        .HasForeignKey("PersonalizadoConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("PersonalizadoConfig");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Producto", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.CategoriaProducto", null)
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaProductoId");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Review", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Producto", "Producto")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("Reviews")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.UserRol", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Rol", "Rol")
                        .WithMany("UserRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("UserRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoCompra", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.DireccionEnvio", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Ingrediente", b =>
                {
                    b.Navigation("ConfiguracionesPersonalizadas");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.MetodoPagoUsuario", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Pedido", b =>
                {
                    b.Navigation("Envio");

                    b.Navigation("Factura");

                    b.Navigation("Historial");

                    b.Navigation("Items");

                    b.Navigation("PersonalizadoConfig");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PersonalizadoConfig", b =>
                {
                    b.Navigation("Ingredientes");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Producto", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("PedidoItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Rol", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.TipoMetodoPago", b =>
                {
                    b.Navigation("MetodosPagoUsuarios");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.User", b =>
                {
                    b.Navigation("CarritoCompra");

                    b.Navigation("Direcciones");

                    b.Navigation("EnviosAsignados");

                    b.Navigation("MetodosPago");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
