// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PastisserieAPI.Infrastructure.Data;

#nullable disable

namespace PastisserieAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_CarritosCompra_UsuarioId");

                    b.ToTable("CarritosCompra", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReservaHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ReservaHasta")
                        .HasDatabaseName("IX_CarritoItems_ReservaHasta");

                    b.HasIndex("CarritoId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("IX_CarritoItems_CarritoId_ProductoId");

                    b.ToTable("CarritoItems", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_CategoriasProducto_Nombre");

                    b.ToTable("CategoriasProducto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Descripcion = "Tortas y pasteles",
                            Nombre = "Tortas"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Descripcion = "Variedad de panes artesanales",
                            Nombre = "Panes"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Descripcion = "Postres y dulces",
                            Nombre = "Postres"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Descripcion = "Galletas caseras",
                            Nombre = "Galletas"
                        });
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.DireccionEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barrio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsPredeterminada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_DireccionesEnvio_UsuarioId");

                    b.HasIndex("UsuarioId", "EsPredeterminada")
                        .HasDatabaseName("IX_DireccionesEnvio_UsuarioId_EsPredeterminada");

                    b.ToTable("DireccionesEnvio", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDespacho")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroGuia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Envios_Estado");

                    b.HasIndex("PedidoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Envios_PedidoId");

                    b.HasIndex("RepartidorId", "Estado")
                        .HasDatabaseName("IX_Envios_RepartidorId_Estado");

                    b.ToTable("Envios", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFactura")
                        .IsUnique()
                        .HasDatabaseName("IX_Facturas_NumeroFactura");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLeida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Fecha")
                        .HasDatabaseName("IX_Notificaciones_UsuarioId_Fecha");

                    b.HasIndex("UsuarioId", "Leida")
                        .HasDatabaseName("IX_Notificaciones_UsuarioId_Leida");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DireccionEnvioId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Efectivo");

                    b.Property<string>("NotasCliente")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransaccionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DireccionEnvioId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Pedidos_Estado");

                    b.HasIndex("EstadoPago")
                        .HasDatabaseName("IX_Pedidos_EstadoPago");

                    b.HasIndex("FechaPedido")
                        .HasDatabaseName("IX_Pedidos_FechaPedido");

                    b.HasIndex("UsuarioId", "Estado")
                        .HasDatabaseName("IX_Pedidos_UsuarioId_Estado");

                    b.HasIndex("UsuarioId", "FechaPedido")
                        .HasDatabaseName("IX_Pedidos_UsuarioId_FechaPedido");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PedidoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CambiadoPor")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("IX_PedidoHistoriales_PedidoId");

                    b.ToTable("PedidoHistoriales", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("IX_PedidoItems_PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PedidoItems", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_Productos_Activo");

                    b.HasIndex("CategoriaProductoId")
                        .HasDatabaseName("IX_Productos_CategoriaProductoId");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Productos_Nombre");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprobada")
                        .HasColumnType("bit");

                    b.Property<int?>("AprobadaPor")
                        .HasColumnType("int");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "Aprobada")
                        .HasDatabaseName("IX_Reviews_ProductoId_Aprobada");

                    b.HasIndex("UsuarioId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("IX_Reviews_UsuarioId_ProductoId_Unique");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Nombre");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Usuario"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "Domiciliario"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Gerente"
                        });
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.UserRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRoles_UsuarioId_RolId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoCompra", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithOne("CarritoCompra")
                        .HasForeignKey("PastisserieAPI.Core.Entities.CarritoCompra", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoItem", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.CarritoCompra", "Carrito")
                        .WithMany("Items")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.Producto", "Producto")
                        .WithMany("CarritoItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.DireccionEnvio", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Envio", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithOne("Envio")
                        .HasForeignKey("PastisserieAPI.Core.Entities.Envio", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Repartidor")
                        .WithMany("EnviosAsignados")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Factura", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithOne("Factura")
                        .HasForeignKey("PastisserieAPI.Core.Entities.Factura", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Notificacion", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Pedido", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.DireccionEnvio", "DireccionEnvio")
                        .WithMany("Pedidos")
                        .HasForeignKey("DireccionEnvioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DireccionEnvio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PedidoHistorial", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithMany("Historial")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.PedidoItem", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.Producto", "Producto")
                        .WithMany("PedidoItems")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Producto", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.CategoriaProducto", "CategoriaProducto")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaProducto");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Review", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Producto", "Producto")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("Reviews")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.UserRol", b =>
                {
                    b.HasOne("PastisserieAPI.Core.Entities.Rol", "Rol")
                        .WithMany("UserRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PastisserieAPI.Core.Entities.User", "Usuario")
                        .WithMany("UserRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CarritoCompra", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.DireccionEnvio", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Pedido", b =>
                {
                    b.Navigation("Envio");

                    b.Navigation("Factura");

                    b.Navigation("Historial");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Producto", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("PedidoItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.Rol", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PastisserieAPI.Core.Entities.User", b =>
                {
                    b.Navigation("CarritoCompra");

                    b.Navigation("Direcciones");

                    b.Navigation("EnviosAsignados");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
